#pragma once

#include <cppdotnet/System/Diagnostics/Activity.hpp>
#include <cppdotnet/System/Diagnostics/ActivityListener.hpp>
#include <cppdotnet/System/Diagnostics/ActivitySamplingResult.hpp>
#include <cppdotnet/System/Diagnostics/ActivitySource.hpp>
#include <cppdotnet/System/Diagnostics/ActivitySpanId.hpp>
#include <cppdotnet/System/Diagnostics/ActivityTraceId.hpp>
#include <cppdotnet/System/Diagnostics/BooleanSwitch.hpp>
#include <cppdotnet/System/Diagnostics/ConsoleTraceListener.hpp>
#include <cppdotnet/System/Diagnostics/Debug.hpp>
#include <cppdotnet/System/Diagnostics/Debugger.hpp>
#include <cppdotnet/System/Diagnostics/DefaultTraceListener.hpp>
#include <cppdotnet/System/Diagnostics/DiagnosticsListener.hpp>
#include <cppdotnet/System/Diagnostics/DiagnosticsSource.hpp>
#include <cppdotnet/System/Diagnostics/EventTypeFilter.hpp>
#include <cppdotnet/System/Diagnostics/ExceptionRecorder.hpp>
#include <cppdotnet/System/Diagnostics/SampleActivity.hpp>
#include <cppdotnet/System/Diagnostics/SourceFilter.hpp>
#include <cppdotnet/System/Diagnostics/SourceLevels.hpp>
#include <cppdotnet/System/Diagnostics/SourceSwitch.hpp>
#include <cppdotnet/System/Diagnostics/Stopwatch.hpp>
#include <cppdotnet/System/Diagnostics/Switch.hpp>
#include <cppdotnet/System/Diagnostics/TagList.hpp>
#include <cppdotnet/System/Diagnostics/TextWriterTraceListener.hpp>
#include <cppdotnet/System/Diagnostics/Trace.hpp>
#include <cppdotnet/System/Diagnostics/TraceEventCache.hpp>
#include <cppdotnet/System/Diagnostics/TraceEventType.hpp>
#include <cppdotnet/System/Diagnostics/TraceFilter.hpp>
#include <cppdotnet/System/Diagnostics/TraceLevel.hpp>
#include <cppdotnet/System/Diagnostics/TraceListener.hpp>
#include <cppdotnet/System/Diagnostics/TraceListenerCollection.hpp>
#include <cppdotnet/System/Diagnostics/TraceOptions.hpp>
#include <cppdotnet/System/Diagnostics/TraceSource.hpp>
#include <cppdotnet/System/Diagnostics/TraceSwitch.hpp>