# MODULE Rules
#%.o : %.cpp
#	@$(CXX) $(CPPFLAGS) $(CXX_STANDARD) $(INC_PARAMS) -fmodules-ts -MMD -MP -c -x c++ $< -o $@

%.o : %.ixx
	$(CXX) $(CPPFLAGS) $(CXX_STANDARD) $(INC_PARAMS) -fmodules-ts -c -x c++ $< -o $(BUILD_DIR)/$@

.PHONY: %.c++m
%.c++m : %.gcm
	@echo YO!
#	@$(CXX) $(CPPFLAGS) $(CXX_STANDARD) $(INC_PARAMS) -fmodules-ts -MMD -MP -c -x c++ $<

#$(CXX_MODULE_PREFIX)/%.gcm :| $(BUILD_DIR)/%.o
#	@$(CXX) $(CPPFLAGS) $(CXX_STANDARD) $(INC_PARAMS) -fmodules-ts -MMD -MP -c -x c++ $<

#"%".c++m : $(CXX_MODULE_PREFIX)/%.gcmu
#	@echo Compile USER header unit

#<%>.c++m : %.gcms
#	@echo Compiling System Header Unit $(patsubst <%>.c++m,<%>,$@)
#	@$(CXX) $(CPPFLAGS) $(CXX_STANDARD) $(INC_PARAMS) -fmodules-ts -c -x c++-system-header $(patsubst %.gcm,%,$@)
#	@echo Compile SYSTEM header unit
#	@$(COMPILE.cc) $(CPPFLAGS) $(CXX_STANDARD) $(INC_PARAMS) -fmodules-ts -x c++-system-header $(patsubst $(SYSTEM_HEADER_FILE_DIR)/%,%,$<)

#$(CXX_MODULE_PREFIX)/%.gcmu : %
#	$(COMPILE.cc) $(call CXX_MODULE_HEADER, "$*") $<

#%.gcms : %
#	$(COMPILE.cc) $(call CXX_MODULE_HEADER, <$*>) $<

# Compiler Header Unit Generation Rule
system_header_units.generated: $(SYSTEM_COMPILER_HEADER_UNIT_GCMS_FILES) $(SYSTEM_HEADER_UNIT_GCMS_FILES)
	@touch $(BUILD_DIR)/$@
	@echo System Header Units Generated!

%.gcms : | $(BUILD_DIR)
	@echo Compiling System Header Unit $(patsubst %.gcms,\<%\>,$@)
	@mkdir -p $(dir $(BUILD_DIR)/$@)
	@$(CXX) $(CPPFLAGS) $(CXX_STANDARD) $(INC_PARAMS) -fmodules-ts -c -x c++-system-header $(patsubst %.gcms,%,$@)
	@touch $(BUILD_DIR)/$@

$(BUILD_DIR) :
	@mkdir -p $(BUILD_DIR)

# Dependencies
dependencies.generated : $(SYSTEM_MODULE_DEPS)
	@touch $(BUILD_DIR)/$@
	@echo System Module Dependencies Generated!

$(SYSTEM_MODULE_DEPS) : system_header_units.generated
	@echo Generating dependency file $@
	@mkdir -p ${dir $(BUILD_DIR)/$@}
	@$(CXX) $(CPPFLAGS) $(CXX_STANDARD) $(INC_PARAMS) -fmodules-ts -MMD -MP -MF $(BUILD_DIR)/$@ -c -x c++ -o $(patsubst %.d,$(BUILD_DIR)/%.o,$@) $(patsubst %.d,$(SRC_DIR)/%.ixx,$@)
	@rm $(patsubst %.d,$(BUILD_DIR)/%.o,$@)

normalized_dependencies.generated : $(NORMALIZED_DEPS)
	@touch $(BUILD_DIR)/$@
	@echo System Module Normalized Dependencies Generated!

$(NORMALIZED_DEPS) : dependencies.generated
	@echo Generating normalized dependency file $@
	@$(call NORMALIZE_DEP_FILE,$(patsubst %.normalized.d,%.d,$(BUILD_DIR)/$@),$(BUILD_DIR)/$@)

# Cause any target referencing this to be executed
FORCE: ;
