#pragma once

import "System/Diagnostics/Activity.hpp";
//#include "System/Diagnostics/ActivityListener.hpp"
import "System/Diagnostics/ActivitySource.hpp";
import "System/Diagnostics/BooleanSwitch.hpp";
import "System/Diagnostics/Trace.hpp";
import "System/Diagnostics/TraceEventType.hpp";
import "System/Diagnostics/TraceLevel.hpp";
import "System/Diagnostics/TraceOptions.hpp";
import "System/Diagnostics/TraceListener.hpp";
import "System/Diagnostics/TraceFilter.hpp";
import "System/Diagnostics/TraceOptions.hpp";
import "System/Diagnostics/TraceSource.hpp";
import "System/Diagnostics/TraceListenerCollection.hpp";
import "System/Diagnostics/DefaultTraceListener.hpp";
import "System/Diagnostics/ConsoleTraceListener.hpp";
import "System/Diagnostics/TextWriterTraceListener.hpp";
import "System/Diagnostics/Debug.hpp";
import "System/Diagnostics/Debugger.hpp";
import "System/Diagnostics/DefaultTraceListener.hpp";
//#include "System/Diagnostics/DiagnosticListener.hpp"
import "System/Diagnostics/DiagnosticSource.hpp";